#!/bin/bash

#SBATCH -J V_U1h2       # job name
#SBATCH -o V_U1h2.o%j    # output and error file name 
#SBATCH -e V_U1h2.e%j    # 
#SBATCH -N 2    # total number of nodes
#SBATCH -n 128    # total number of mpi tasks requested (max = 68x4 = 272)
#SBATCH -p normal    # queue (partition) or normal
#SBATCH -t 48:00:00    # queue (partition) or normal
#SBATCH --mail-user=bul201@psu.edu  
#SBATCH --mail-type=begin # email me when the job starts  
#SBATCH --mail-type=end   # email me when the job finishes  

module list # load my personal default collection of modules 

pwd
date 

export IROOT=/opt/intel/compilers_and_libraries_2018.2.199/linux
export MPI_ROOT=$IROOT/mpi/intel64

source $WORK/OpenFOAM/OpenFOAM-5.x/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions # Source run functions


decomposePar -region surface
decomposePar -region subsurface

runParallel $(getApplication)

reconstructPar -region surface
reconstructPar -region subsurface
